{
  "formatVersion": "1.1",
  "component": {
    "group": "io.gonative.android",
    "module": "icons",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "icons-1.2.0.aar",
          "url": "icons-1.2.0.aar",
          "size": 2124591,
          "sha512": "48b5c1cd716ee31c6cb816c222cddef0fe113bf7cfb96ae3226653b0e01f08cdb5178bd4376a66830ce0f6f12480a051876f35dce759ce2c4685bae7e5318dbc",
          "sha256": "197acc30464fcc6edac4763bd1a515f6d1480a960a4beaa27a0dd09408249e96",
          "sha1": "e96620600c2bd80fa9cc2c4c7f13fd1b9e7facf4",
          "md5": "de4612bb50b166e37dadf06a8edfca8a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "icons-1.2.0.aar",
          "url": "icons-1.2.0.aar",
          "size": 2124591,
          "sha512": "48b5c1cd716ee31c6cb816c222cddef0fe113bf7cfb96ae3226653b0e01f08cdb5178bd4376a66830ce0f6f12480a051876f35dce759ce2c4685bae7e5318dbc",
          "sha256": "197acc30464fcc6edac4763bd1a515f6d1480a960a4beaa27a0dd09408249e96",
          "sha1": "e96620600c2bd80fa9cc2c4c7f13fd1b9e7facf4",
          "md5": "de4612bb50b166e37dadf06a8edfca8a"
        }
      ]
    }
  ]
}
