{
  "formatVersion": "1.1",
  "component": {
    "group": "io.gonative.android",
    "module": "icons",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "icons-1.0.aar",
          "url": "icons-1.0.aar",
          "size": 2135329,
          "sha512": "356ec5bfb8f3b3d4262635e21e201eff595de151c965b170a1d3615703197e33a4f9fe66e3f3541e1a2b2bf5d9cbfcdb931d84d377ef74d4108642a25d0d8466",
          "sha256": "54fa3124e76881ae0db4c8b9b027d78606364eb7c19d7646f42e6c5201ac6fad",
          "sha1": "7cbc750b582a6a03b27b5f8debaedb5a6025a461",
          "md5": "370f8b477e39685d85d9568ea5f16906"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "icons-1.0.aar",
          "url": "icons-1.0.aar",
          "size": 2135329,
          "sha512": "356ec5bfb8f3b3d4262635e21e201eff595de151c965b170a1d3615703197e33a4f9fe66e3f3541e1a2b2bf5d9cbfcdb931d84d377ef74d4108642a25d0d8466",
          "sha256": "54fa3124e76881ae0db4c8b9b027d78606364eb7c19d7646f42e6c5201ac6fad",
          "sha1": "7cbc750b582a6a03b27b5f8debaedb5a6025a461",
          "md5": "370f8b477e39685d85d9568ea5f16906"
        }
      ]
    }
  ]
}
