{
  "formatVersion": "1.1",
  "component": {
    "group": "io.gonative.android",
    "module": "icons",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "icons-1.0.aar",
          "url": "icons-1.0.aar",
          "size": 2123510,
          "sha512": "61dd44ba17c6ec1d258fc99ea06a223063a99983b0ece535feace258ba24e8d961d96921ad6eeb5912e1be0670e92a4cad99d63f20ba89c32041262231d2287e",
          "sha256": "cae4fc98dd74cb790c3c4ab6e73e27427ee9cb5514f7b2000d879a9c6cd41e90",
          "sha1": "c371c5720e0cbda506fc8beed1404140c2ab56ef",
          "md5": "4b2b1558a83468af9beaf976c922880e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "icons-1.0.aar",
          "url": "icons-1.0.aar",
          "size": 2123510,
          "sha512": "61dd44ba17c6ec1d258fc99ea06a223063a99983b0ece535feace258ba24e8d961d96921ad6eeb5912e1be0670e92a4cad99d63f20ba89c32041262231d2287e",
          "sha256": "cae4fc98dd74cb790c3c4ab6e73e27427ee9cb5514f7b2000d879a9c6cd41e90",
          "sha1": "c371c5720e0cbda506fc8beed1404140c2ab56ef",
          "md5": "4b2b1558a83468af9beaf976c922880e"
        }
      ]
    }
  ]
}
