{
  "formatVersion": "1.1",
  "component": {
    "group": "io.gonative.android",
    "module": "core",
    "version": "1.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-1.3.2.aar",
          "url": "core-1.3.2.aar",
          "size": 26443,
          "sha512": "64faef7a1cad3cec0ae69ebc8500a89008ba6e6ba79614cd668a8f68150b8fa7062307d9c3ca9180c59eed10752020dda3bf7ad325a360348d3b229c5bebe32c",
          "sha256": "9b32c219927315afc86cded5a146ae24d1cf73e4c3b356050f463fb9f95a34f8",
          "sha1": "2e44a5ad2a06c50842553ac9d914dec0520a2388",
          "md5": "093d46322cc4ea4b0b389a1503432c9d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.github.gonativeio",
          "module": "gonative-android-library",
          "version": {
            "requires": "1.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.3.2.aar",
          "url": "core-1.3.2.aar",
          "size": 26443,
          "sha512": "64faef7a1cad3cec0ae69ebc8500a89008ba6e6ba79614cd668a8f68150b8fa7062307d9c3ca9180c59eed10752020dda3bf7ad325a360348d3b229c5bebe32c",
          "sha256": "9b32c219927315afc86cded5a146ae24d1cf73e4c3b356050f463fb9f95a34f8",
          "sha1": "2e44a5ad2a06c50842553ac9d914dec0520a2388",
          "md5": "093d46322cc4ea4b0b389a1503432c9d"
        }
      ]
    }
  ]
}
